name: PHPStan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ '8.4', '8.5' ]

    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - uses: actions/cache@v5
        with:
          path: vendor
          key: composer-${{ matrix.php-version }}-${{ hashFiles('composer.lock', 'composer.json') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-
            composer-
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - run: vendor/bin/phpstan analyse